Traceback (most recent call last):
  File "/Users/cfirhadar/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/cfirhadar/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/cfirhadar/miniconda3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/cfirhadar/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/cfirhadar/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/cfirhadar/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/cfirhadar/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# reshaping to rows, timestamps, features
X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[10], line 2[0m
[1;32m      1[0m [38;5;66;03m# reshaping to rows, timestamps, features[39;00m
[0;32m----> 2[0m X_train [38;5;241m=[39m [43mX_train[49m[38;5;241;43m.[39;49m[43mreshape[49m(X_train[38;5;241m.[39mshape[[38;5;241m0[39m], [38;5;241m1[39m, X_train[38;5;241m.[39mshape[[38;5;241m1[39m])
[1;32m      3[0m X_test [38;5;241m=[39m X_test[38;5;241m.[39mreshape(X_test[38;5;241m.[39mshape[[38;5;241m0[39m], [38;5;241m1[39m, X_test[38;5;241m.[39mshape[[38;5;241m1[39m])

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'reshape'

